# Generated by Django 5.0.4 on 2024-05-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_follow_follow_unique_followship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
