# Generated by Django 5.0.4 on 2024-05-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(choices=[('AM', 'amazon'), ('UI', 'ui/ux'), ('PH', 'physics'), ('FR', 'frontend'), ('BA', 'backend')], max_length=2, null=True),
        ),
    ]
